# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.4/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/prasansamtani/Documents/GitHub/roop/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/prasansamtani/Documents/GitHub/roop

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/prasansamtani/Documents/GitHub/roop/CMakeFiles /Users/prasansamtani/Documents/GitHub/roop//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/prasansamtani/Documents/GitHub/roop/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sexpr

# Build rule for target.
sexpr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sexpr
.PHONY : sexpr

# fast build rule for target.
sexpr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/build
.PHONY : sexpr/fast

#=============================================================================
# Target rules for targets named tinyscheme

# Build rule for target.
tinyscheme: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tinyscheme
.PHONY : tinyscheme

# fast build rule for target.
tinyscheme/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyscheme.dir/build.make CMakeFiles/tinyscheme.dir/build
.PHONY : tinyscheme/fast

#=============================================================================
# Target rules for targets named Roop

# Build rule for target.
Roop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Roop
.PHONY : Roop

# fast build rule for target.
Roop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/build
.PHONY : Roop/fast

Blur.o: Blur.cpp.o
.PHONY : Blur.o

# target to build an object file
Blur.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Blur.cpp.o
.PHONY : Blur.cpp.o

Blur.i: Blur.cpp.i
.PHONY : Blur.i

# target to preprocess a source file
Blur.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Blur.cpp.i
.PHONY : Blur.cpp.i

Blur.s: Blur.cpp.s
.PHONY : Blur.s

# target to generate assembly for a file
Blur.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Blur.cpp.s
.PHONY : Blur.cpp.s

Canny.o: Canny.cpp.o
.PHONY : Canny.o

# target to build an object file
Canny.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Canny.cpp.o
.PHONY : Canny.cpp.o

Canny.i: Canny.cpp.i
.PHONY : Canny.i

# target to preprocess a source file
Canny.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Canny.cpp.i
.PHONY : Canny.cpp.i

Canny.s: Canny.cpp.s
.PHONY : Canny.s

# target to generate assembly for a file
Canny.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Canny.cpp.s
.PHONY : Canny.cpp.s

ColorConversions.o: ColorConversions.cpp.o
.PHONY : ColorConversions.o

# target to build an object file
ColorConversions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/ColorConversions.cpp.o
.PHONY : ColorConversions.cpp.o

ColorConversions.i: ColorConversions.cpp.i
.PHONY : ColorConversions.i

# target to preprocess a source file
ColorConversions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/ColorConversions.cpp.i
.PHONY : ColorConversions.cpp.i

ColorConversions.s: ColorConversions.cpp.s
.PHONY : ColorConversions.s

# target to generate assembly for a file
ColorConversions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/ColorConversions.cpp.s
.PHONY : ColorConversions.cpp.s

ConnectedComponents.o: ConnectedComponents.cpp.o
.PHONY : ConnectedComponents.o

# target to build an object file
ConnectedComponents.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/ConnectedComponents.cpp.o
.PHONY : ConnectedComponents.cpp.o

ConnectedComponents.i: ConnectedComponents.cpp.i
.PHONY : ConnectedComponents.i

# target to preprocess a source file
ConnectedComponents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/ConnectedComponents.cpp.i
.PHONY : ConnectedComponents.cpp.i

ConnectedComponents.s: ConnectedComponents.cpp.s
.PHONY : ConnectedComponents.s

# target to generate assembly for a file
ConnectedComponents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/ConnectedComponents.cpp.s
.PHONY : ConnectedComponents.cpp.s

DefGet.o: DefGet.cpp.o
.PHONY : DefGet.o

# target to build an object file
DefGet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/DefGet.cpp.o
.PHONY : DefGet.cpp.o

DefGet.i: DefGet.cpp.i
.PHONY : DefGet.i

# target to preprocess a source file
DefGet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/DefGet.cpp.i
.PHONY : DefGet.cpp.i

DefGet.s: DefGet.cpp.s
.PHONY : DefGet.s

# target to generate assembly for a file
DefGet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/DefGet.cpp.s
.PHONY : DefGet.cpp.s

Derivative.o: Derivative.cpp.o
.PHONY : Derivative.o

# target to build an object file
Derivative.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Derivative.cpp.o
.PHONY : Derivative.cpp.o

Derivative.i: Derivative.cpp.i
.PHONY : Derivative.i

# target to preprocess a source file
Derivative.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Derivative.cpp.i
.PHONY : Derivative.cpp.i

Derivative.s: Derivative.cpp.s
.PHONY : Derivative.s

# target to generate assembly for a file
Derivative.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Derivative.cpp.s
.PHONY : Derivative.cpp.s

EnhanceContrast.o: EnhanceContrast.cpp.o
.PHONY : EnhanceContrast.o

# target to build an object file
EnhanceContrast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/EnhanceContrast.cpp.o
.PHONY : EnhanceContrast.cpp.o

EnhanceContrast.i: EnhanceContrast.cpp.i
.PHONY : EnhanceContrast.i

# target to preprocess a source file
EnhanceContrast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/EnhanceContrast.cpp.i
.PHONY : EnhanceContrast.cpp.i

EnhanceContrast.s: EnhanceContrast.cpp.s
.PHONY : EnhanceContrast.s

# target to generate assembly for a file
EnhanceContrast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/EnhanceContrast.cpp.s
.PHONY : EnhanceContrast.cpp.s

ExecutableCommand.o: ExecutableCommand.cpp.o
.PHONY : ExecutableCommand.o

# target to build an object file
ExecutableCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/ExecutableCommand.cpp.o
.PHONY : ExecutableCommand.cpp.o

ExecutableCommand.i: ExecutableCommand.cpp.i
.PHONY : ExecutableCommand.i

# target to preprocess a source file
ExecutableCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/ExecutableCommand.cpp.i
.PHONY : ExecutableCommand.cpp.i

ExecutableCommand.s: ExecutableCommand.cpp.s
.PHONY : ExecutableCommand.s

# target to generate assembly for a file
ExecutableCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/ExecutableCommand.cpp.s
.PHONY : ExecutableCommand.cpp.s

FileOperations.o: FileOperations.cpp.o
.PHONY : FileOperations.o

# target to build an object file
FileOperations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/FileOperations.cpp.o
.PHONY : FileOperations.cpp.o

FileOperations.i: FileOperations.cpp.i
.PHONY : FileOperations.i

# target to preprocess a source file
FileOperations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/FileOperations.cpp.i
.PHONY : FileOperations.cpp.i

FileOperations.s: FileOperations.cpp.s
.PHONY : FileOperations.s

# target to generate assembly for a file
FileOperations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/FileOperations.cpp.s
.PHONY : FileOperations.cpp.s

Filter3.o: Filter3.cpp.o
.PHONY : Filter3.o

# target to build an object file
Filter3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Filter3.cpp.o
.PHONY : Filter3.cpp.o

Filter3.i: Filter3.cpp.i
.PHONY : Filter3.i

# target to preprocess a source file
Filter3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Filter3.cpp.i
.PHONY : Filter3.cpp.i

Filter3.s: Filter3.cpp.s
.PHONY : Filter3.s

# target to generate assembly for a file
Filter3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Filter3.cpp.s
.PHONY : Filter3.cpp.s

ForEachPixel.o: ForEachPixel.cpp.o
.PHONY : ForEachPixel.o

# target to build an object file
ForEachPixel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/ForEachPixel.cpp.o
.PHONY : ForEachPixel.cpp.o

ForEachPixel.i: ForEachPixel.cpp.i
.PHONY : ForEachPixel.i

# target to preprocess a source file
ForEachPixel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/ForEachPixel.cpp.i
.PHONY : ForEachPixel.cpp.i

ForEachPixel.s: ForEachPixel.cpp.s
.PHONY : ForEachPixel.s

# target to generate assembly for a file
ForEachPixel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/ForEachPixel.cpp.s
.PHONY : ForEachPixel.cpp.s

LogicalOperations.o: LogicalOperations.cpp.o
.PHONY : LogicalOperations.o

# target to build an object file
LogicalOperations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/LogicalOperations.cpp.o
.PHONY : LogicalOperations.cpp.o

LogicalOperations.i: LogicalOperations.cpp.i
.PHONY : LogicalOperations.i

# target to preprocess a source file
LogicalOperations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/LogicalOperations.cpp.i
.PHONY : LogicalOperations.cpp.i

LogicalOperations.s: LogicalOperations.cpp.s
.PHONY : LogicalOperations.s

# target to generate assembly for a file
LogicalOperations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/LogicalOperations.cpp.s
.PHONY : LogicalOperations.cpp.s

MorphologicalOperations.o: MorphologicalOperations.cpp.o
.PHONY : MorphologicalOperations.o

# target to build an object file
MorphologicalOperations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/MorphologicalOperations.cpp.o
.PHONY : MorphologicalOperations.cpp.o

MorphologicalOperations.i: MorphologicalOperations.cpp.i
.PHONY : MorphologicalOperations.i

# target to preprocess a source file
MorphologicalOperations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/MorphologicalOperations.cpp.i
.PHONY : MorphologicalOperations.cpp.i

MorphologicalOperations.s: MorphologicalOperations.cpp.s
.PHONY : MorphologicalOperations.s

# target to generate assembly for a file
MorphologicalOperations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/MorphologicalOperations.cpp.s
.PHONY : MorphologicalOperations.cpp.s

Multiply.o: Multiply.cpp.o
.PHONY : Multiply.o

# target to build an object file
Multiply.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Multiply.cpp.o
.PHONY : Multiply.cpp.o

Multiply.i: Multiply.cpp.i
.PHONY : Multiply.i

# target to preprocess a source file
Multiply.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Multiply.cpp.i
.PHONY : Multiply.cpp.i

Multiply.s: Multiply.cpp.s
.PHONY : Multiply.s

# target to generate assembly for a file
Multiply.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Multiply.cpp.s
.PHONY : Multiply.cpp.s

Roop.o: Roop.cpp.o
.PHONY : Roop.o

# target to build an object file
Roop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Roop.cpp.o
.PHONY : Roop.cpp.o

Roop.i: Roop.cpp.i
.PHONY : Roop.i

# target to preprocess a source file
Roop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Roop.cpp.i
.PHONY : Roop.cpp.i

Roop.s: Roop.cpp.s
.PHONY : Roop.s

# target to generate assembly for a file
Roop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Roop.cpp.s
.PHONY : Roop.cpp.s

RoopCommon.o: RoopCommon.cpp.o
.PHONY : RoopCommon.o

# target to build an object file
RoopCommon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/RoopCommon.cpp.o
.PHONY : RoopCommon.cpp.o

RoopCommon.i: RoopCommon.cpp.i
.PHONY : RoopCommon.i

# target to preprocess a source file
RoopCommon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/RoopCommon.cpp.i
.PHONY : RoopCommon.cpp.i

RoopCommon.s: RoopCommon.cpp.s
.PHONY : RoopCommon.s

# target to generate assembly for a file
RoopCommon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/RoopCommon.cpp.s
.PHONY : RoopCommon.cpp.s

Segmentation.o: Segmentation.cpp.o
.PHONY : Segmentation.o

# target to build an object file
Segmentation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Segmentation.cpp.o
.PHONY : Segmentation.cpp.o

Segmentation.i: Segmentation.cpp.i
.PHONY : Segmentation.i

# target to preprocess a source file
Segmentation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Segmentation.cpp.i
.PHONY : Segmentation.cpp.i

Segmentation.s: Segmentation.cpp.s
.PHONY : Segmentation.s

# target to generate assembly for a file
Segmentation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Segmentation.cpp.s
.PHONY : Segmentation.cpp.s

ShapeAnalysis.o: ShapeAnalysis.cpp.o
.PHONY : ShapeAnalysis.o

# target to build an object file
ShapeAnalysis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/ShapeAnalysis.cpp.o
.PHONY : ShapeAnalysis.cpp.o

ShapeAnalysis.i: ShapeAnalysis.cpp.i
.PHONY : ShapeAnalysis.i

# target to preprocess a source file
ShapeAnalysis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/ShapeAnalysis.cpp.i
.PHONY : ShapeAnalysis.cpp.i

ShapeAnalysis.s: ShapeAnalysis.cpp.s
.PHONY : ShapeAnalysis.s

# target to generate assembly for a file
ShapeAnalysis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/ShapeAnalysis.cpp.s
.PHONY : ShapeAnalysis.cpp.s

Sharpen.o: Sharpen.cpp.o
.PHONY : Sharpen.o

# target to build an object file
Sharpen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Sharpen.cpp.o
.PHONY : Sharpen.cpp.o

Sharpen.i: Sharpen.cpp.i
.PHONY : Sharpen.i

# target to preprocess a source file
Sharpen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Sharpen.cpp.i
.PHONY : Sharpen.cpp.i

Sharpen.s: Sharpen.cpp.s
.PHONY : Sharpen.s

# target to generate assembly for a file
Sharpen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Sharpen.cpp.s
.PHONY : Sharpen.cpp.s

Transform.o: Transform.cpp.o
.PHONY : Transform.o

# target to build an object file
Transform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Transform.cpp.o
.PHONY : Transform.cpp.o

Transform.i: Transform.cpp.i
.PHONY : Transform.i

# target to preprocess a source file
Transform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Transform.cpp.i
.PHONY : Transform.cpp.i

Transform.s: Transform.cpp.s
.PHONY : Transform.s

# target to generate assembly for a file
Transform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Roop.dir/build.make CMakeFiles/Roop.dir/Transform.cpp.s
.PHONY : Transform.cpp.s

thirdparty/sexpr-1.2.1/cstring.o: thirdparty/sexpr-1.2.1/cstring.c.o
.PHONY : thirdparty/sexpr-1.2.1/cstring.o

# target to build an object file
thirdparty/sexpr-1.2.1/cstring.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/cstring.c.o
.PHONY : thirdparty/sexpr-1.2.1/cstring.c.o

thirdparty/sexpr-1.2.1/cstring.i: thirdparty/sexpr-1.2.1/cstring.c.i
.PHONY : thirdparty/sexpr-1.2.1/cstring.i

# target to preprocess a source file
thirdparty/sexpr-1.2.1/cstring.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/cstring.c.i
.PHONY : thirdparty/sexpr-1.2.1/cstring.c.i

thirdparty/sexpr-1.2.1/cstring.s: thirdparty/sexpr-1.2.1/cstring.c.s
.PHONY : thirdparty/sexpr-1.2.1/cstring.s

# target to generate assembly for a file
thirdparty/sexpr-1.2.1/cstring.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/cstring.c.s
.PHONY : thirdparty/sexpr-1.2.1/cstring.c.s

thirdparty/sexpr-1.2.1/event_temp.o: thirdparty/sexpr-1.2.1/event_temp.c.o
.PHONY : thirdparty/sexpr-1.2.1/event_temp.o

# target to build an object file
thirdparty/sexpr-1.2.1/event_temp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/event_temp.c.o
.PHONY : thirdparty/sexpr-1.2.1/event_temp.c.o

thirdparty/sexpr-1.2.1/event_temp.i: thirdparty/sexpr-1.2.1/event_temp.c.i
.PHONY : thirdparty/sexpr-1.2.1/event_temp.i

# target to preprocess a source file
thirdparty/sexpr-1.2.1/event_temp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/event_temp.c.i
.PHONY : thirdparty/sexpr-1.2.1/event_temp.c.i

thirdparty/sexpr-1.2.1/event_temp.s: thirdparty/sexpr-1.2.1/event_temp.c.s
.PHONY : thirdparty/sexpr-1.2.1/event_temp.s

# target to generate assembly for a file
thirdparty/sexpr-1.2.1/event_temp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/event_temp.c.s
.PHONY : thirdparty/sexpr-1.2.1/event_temp.c.s

thirdparty/sexpr-1.2.1/faststack.o: thirdparty/sexpr-1.2.1/faststack.c.o
.PHONY : thirdparty/sexpr-1.2.1/faststack.o

# target to build an object file
thirdparty/sexpr-1.2.1/faststack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/faststack.c.o
.PHONY : thirdparty/sexpr-1.2.1/faststack.c.o

thirdparty/sexpr-1.2.1/faststack.i: thirdparty/sexpr-1.2.1/faststack.c.i
.PHONY : thirdparty/sexpr-1.2.1/faststack.i

# target to preprocess a source file
thirdparty/sexpr-1.2.1/faststack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/faststack.c.i
.PHONY : thirdparty/sexpr-1.2.1/faststack.c.i

thirdparty/sexpr-1.2.1/faststack.s: thirdparty/sexpr-1.2.1/faststack.c.s
.PHONY : thirdparty/sexpr-1.2.1/faststack.s

# target to generate assembly for a file
thirdparty/sexpr-1.2.1/faststack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/faststack.c.s
.PHONY : thirdparty/sexpr-1.2.1/faststack.c.s

thirdparty/sexpr-1.2.1/parser.o: thirdparty/sexpr-1.2.1/parser.c.o
.PHONY : thirdparty/sexpr-1.2.1/parser.o

# target to build an object file
thirdparty/sexpr-1.2.1/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/parser.c.o
.PHONY : thirdparty/sexpr-1.2.1/parser.c.o

thirdparty/sexpr-1.2.1/parser.i: thirdparty/sexpr-1.2.1/parser.c.i
.PHONY : thirdparty/sexpr-1.2.1/parser.i

# target to preprocess a source file
thirdparty/sexpr-1.2.1/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/parser.c.i
.PHONY : thirdparty/sexpr-1.2.1/parser.c.i

thirdparty/sexpr-1.2.1/parser.s: thirdparty/sexpr-1.2.1/parser.c.s
.PHONY : thirdparty/sexpr-1.2.1/parser.s

# target to generate assembly for a file
thirdparty/sexpr-1.2.1/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/parser.c.s
.PHONY : thirdparty/sexpr-1.2.1/parser.c.s

thirdparty/sexpr-1.2.1/sexp.o: thirdparty/sexpr-1.2.1/sexp.c.o
.PHONY : thirdparty/sexpr-1.2.1/sexp.o

# target to build an object file
thirdparty/sexpr-1.2.1/sexp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/sexp.c.o
.PHONY : thirdparty/sexpr-1.2.1/sexp.c.o

thirdparty/sexpr-1.2.1/sexp.i: thirdparty/sexpr-1.2.1/sexp.c.i
.PHONY : thirdparty/sexpr-1.2.1/sexp.i

# target to preprocess a source file
thirdparty/sexpr-1.2.1/sexp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/sexp.c.i
.PHONY : thirdparty/sexpr-1.2.1/sexp.c.i

thirdparty/sexpr-1.2.1/sexp.s: thirdparty/sexpr-1.2.1/sexp.c.s
.PHONY : thirdparty/sexpr-1.2.1/sexp.s

# target to generate assembly for a file
thirdparty/sexpr-1.2.1/sexp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/sexp.c.s
.PHONY : thirdparty/sexpr-1.2.1/sexp.c.s

thirdparty/sexpr-1.2.1/sexp_memory.o: thirdparty/sexpr-1.2.1/sexp_memory.c.o
.PHONY : thirdparty/sexpr-1.2.1/sexp_memory.o

# target to build an object file
thirdparty/sexpr-1.2.1/sexp_memory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/sexp_memory.c.o
.PHONY : thirdparty/sexpr-1.2.1/sexp_memory.c.o

thirdparty/sexpr-1.2.1/sexp_memory.i: thirdparty/sexpr-1.2.1/sexp_memory.c.i
.PHONY : thirdparty/sexpr-1.2.1/sexp_memory.i

# target to preprocess a source file
thirdparty/sexpr-1.2.1/sexp_memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/sexp_memory.c.i
.PHONY : thirdparty/sexpr-1.2.1/sexp_memory.c.i

thirdparty/sexpr-1.2.1/sexp_memory.s: thirdparty/sexpr-1.2.1/sexp_memory.c.s
.PHONY : thirdparty/sexpr-1.2.1/sexp_memory.s

# target to generate assembly for a file
thirdparty/sexpr-1.2.1/sexp_memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/sexp_memory.c.s
.PHONY : thirdparty/sexpr-1.2.1/sexp_memory.c.s

thirdparty/sexpr-1.2.1/sexp_ops.o: thirdparty/sexpr-1.2.1/sexp_ops.c.o
.PHONY : thirdparty/sexpr-1.2.1/sexp_ops.o

# target to build an object file
thirdparty/sexpr-1.2.1/sexp_ops.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/sexp_ops.c.o
.PHONY : thirdparty/sexpr-1.2.1/sexp_ops.c.o

thirdparty/sexpr-1.2.1/sexp_ops.i: thirdparty/sexpr-1.2.1/sexp_ops.c.i
.PHONY : thirdparty/sexpr-1.2.1/sexp_ops.i

# target to preprocess a source file
thirdparty/sexpr-1.2.1/sexp_ops.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/sexp_ops.c.i
.PHONY : thirdparty/sexpr-1.2.1/sexp_ops.c.i

thirdparty/sexpr-1.2.1/sexp_ops.s: thirdparty/sexpr-1.2.1/sexp_ops.c.s
.PHONY : thirdparty/sexpr-1.2.1/sexp_ops.s

# target to generate assembly for a file
thirdparty/sexpr-1.2.1/sexp_ops.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/sexp_ops.c.s
.PHONY : thirdparty/sexpr-1.2.1/sexp_ops.c.s

thirdparty/sexpr-1.2.1/sexp_vis.o: thirdparty/sexpr-1.2.1/sexp_vis.c.o
.PHONY : thirdparty/sexpr-1.2.1/sexp_vis.o

# target to build an object file
thirdparty/sexpr-1.2.1/sexp_vis.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/sexp_vis.c.o
.PHONY : thirdparty/sexpr-1.2.1/sexp_vis.c.o

thirdparty/sexpr-1.2.1/sexp_vis.i: thirdparty/sexpr-1.2.1/sexp_vis.c.i
.PHONY : thirdparty/sexpr-1.2.1/sexp_vis.i

# target to preprocess a source file
thirdparty/sexpr-1.2.1/sexp_vis.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/sexp_vis.c.i
.PHONY : thirdparty/sexpr-1.2.1/sexp_vis.c.i

thirdparty/sexpr-1.2.1/sexp_vis.s: thirdparty/sexpr-1.2.1/sexp_vis.c.s
.PHONY : thirdparty/sexpr-1.2.1/sexp_vis.s

# target to generate assembly for a file
thirdparty/sexpr-1.2.1/sexp_vis.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sexpr.dir/build.make CMakeFiles/sexpr.dir/thirdparty/sexpr-1.2.1/sexp_vis.c.s
.PHONY : thirdparty/sexpr-1.2.1/sexp_vis.c.s

thirdparty/tinyscheme-1.41/scheme.o: thirdparty/tinyscheme-1.41/scheme.c.o
.PHONY : thirdparty/tinyscheme-1.41/scheme.o

# target to build an object file
thirdparty/tinyscheme-1.41/scheme.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyscheme.dir/build.make CMakeFiles/tinyscheme.dir/thirdparty/tinyscheme-1.41/scheme.c.o
.PHONY : thirdparty/tinyscheme-1.41/scheme.c.o

thirdparty/tinyscheme-1.41/scheme.i: thirdparty/tinyscheme-1.41/scheme.c.i
.PHONY : thirdparty/tinyscheme-1.41/scheme.i

# target to preprocess a source file
thirdparty/tinyscheme-1.41/scheme.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyscheme.dir/build.make CMakeFiles/tinyscheme.dir/thirdparty/tinyscheme-1.41/scheme.c.i
.PHONY : thirdparty/tinyscheme-1.41/scheme.c.i

thirdparty/tinyscheme-1.41/scheme.s: thirdparty/tinyscheme-1.41/scheme.c.s
.PHONY : thirdparty/tinyscheme-1.41/scheme.s

# target to generate assembly for a file
thirdparty/tinyscheme-1.41/scheme.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyscheme.dir/build.make CMakeFiles/tinyscheme.dir/thirdparty/tinyscheme-1.41/scheme.c.s
.PHONY : thirdparty/tinyscheme-1.41/scheme.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Roop"
	@echo "... sexpr"
	@echo "... tinyscheme"
	@echo "... Blur.o"
	@echo "... Blur.i"
	@echo "... Blur.s"
	@echo "... Canny.o"
	@echo "... Canny.i"
	@echo "... Canny.s"
	@echo "... ColorConversions.o"
	@echo "... ColorConversions.i"
	@echo "... ColorConversions.s"
	@echo "... ConnectedComponents.o"
	@echo "... ConnectedComponents.i"
	@echo "... ConnectedComponents.s"
	@echo "... DefGet.o"
	@echo "... DefGet.i"
	@echo "... DefGet.s"
	@echo "... Derivative.o"
	@echo "... Derivative.i"
	@echo "... Derivative.s"
	@echo "... EnhanceContrast.o"
	@echo "... EnhanceContrast.i"
	@echo "... EnhanceContrast.s"
	@echo "... ExecutableCommand.o"
	@echo "... ExecutableCommand.i"
	@echo "... ExecutableCommand.s"
	@echo "... FileOperations.o"
	@echo "... FileOperations.i"
	@echo "... FileOperations.s"
	@echo "... Filter3.o"
	@echo "... Filter3.i"
	@echo "... Filter3.s"
	@echo "... ForEachPixel.o"
	@echo "... ForEachPixel.i"
	@echo "... ForEachPixel.s"
	@echo "... LogicalOperations.o"
	@echo "... LogicalOperations.i"
	@echo "... LogicalOperations.s"
	@echo "... MorphologicalOperations.o"
	@echo "... MorphologicalOperations.i"
	@echo "... MorphologicalOperations.s"
	@echo "... Multiply.o"
	@echo "... Multiply.i"
	@echo "... Multiply.s"
	@echo "... Roop.o"
	@echo "... Roop.i"
	@echo "... Roop.s"
	@echo "... RoopCommon.o"
	@echo "... RoopCommon.i"
	@echo "... RoopCommon.s"
	@echo "... Segmentation.o"
	@echo "... Segmentation.i"
	@echo "... Segmentation.s"
	@echo "... ShapeAnalysis.o"
	@echo "... ShapeAnalysis.i"
	@echo "... ShapeAnalysis.s"
	@echo "... Sharpen.o"
	@echo "... Sharpen.i"
	@echo "... Sharpen.s"
	@echo "... Transform.o"
	@echo "... Transform.i"
	@echo "... Transform.s"
	@echo "... thirdparty/sexpr-1.2.1/cstring.o"
	@echo "... thirdparty/sexpr-1.2.1/cstring.i"
	@echo "... thirdparty/sexpr-1.2.1/cstring.s"
	@echo "... thirdparty/sexpr-1.2.1/event_temp.o"
	@echo "... thirdparty/sexpr-1.2.1/event_temp.i"
	@echo "... thirdparty/sexpr-1.2.1/event_temp.s"
	@echo "... thirdparty/sexpr-1.2.1/faststack.o"
	@echo "... thirdparty/sexpr-1.2.1/faststack.i"
	@echo "... thirdparty/sexpr-1.2.1/faststack.s"
	@echo "... thirdparty/sexpr-1.2.1/parser.o"
	@echo "... thirdparty/sexpr-1.2.1/parser.i"
	@echo "... thirdparty/sexpr-1.2.1/parser.s"
	@echo "... thirdparty/sexpr-1.2.1/sexp.o"
	@echo "... thirdparty/sexpr-1.2.1/sexp.i"
	@echo "... thirdparty/sexpr-1.2.1/sexp.s"
	@echo "... thirdparty/sexpr-1.2.1/sexp_memory.o"
	@echo "... thirdparty/sexpr-1.2.1/sexp_memory.i"
	@echo "... thirdparty/sexpr-1.2.1/sexp_memory.s"
	@echo "... thirdparty/sexpr-1.2.1/sexp_ops.o"
	@echo "... thirdparty/sexpr-1.2.1/sexp_ops.i"
	@echo "... thirdparty/sexpr-1.2.1/sexp_ops.s"
	@echo "... thirdparty/sexpr-1.2.1/sexp_vis.o"
	@echo "... thirdparty/sexpr-1.2.1/sexp_vis.i"
	@echo "... thirdparty/sexpr-1.2.1/sexp_vis.s"
	@echo "... thirdparty/tinyscheme-1.41/scheme.o"
	@echo "... thirdparty/tinyscheme-1.41/scheme.i"
	@echo "... thirdparty/tinyscheme-1.41/scheme.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

